// Ping request

GET http://localhost:8080/ping

###
// Create User by sending user info in body
// Http POST request
POST http://localhost:8080/users

{
    "first_name": "Test",
    "last_name":"Reddy",
    "email_id" : "test@test.com"
}

###
// Read User by id
// Http GET request

GET http://localhost:8080/users/2


###
// Delete the user by id
// TODO: Assignment

DELETE http://localhost:8080/users/123